run_metadata:
  description: Write an array
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: http://data.scrc.uk/api/
  default_input_namespace: martinburke
  default_output_namespace: martinburke
  write_data_store: /media/martin/storage/projects/AtomProjects/DataRegistryUtils.jl/examples/simple2/data/
  local_repo: /media/martin/storage/projects/AtomProjects/DataRegistryUtils.jl/
  latest_commit: 221bfe8b52bbfb3b2dbdc23037b7dd94b49aaa70
  remote_repo: https://github.com/FAIRDataPipeline/DataRegistryUtils.jl
  script: |-
        R -f simple_working_examples/read_csv.R /Users/SoniaM/datastore/coderun/20210511-231444/

write:
- data_product: test/csv
  description: test csv file with simple data
  file_type: csv
  use:
    version: 0.0.1
    public: true
