run_metadata:
  description: Read an array
  local_data_registry_url: https://localhost:8000/api/
  remote_data_registry_url: https://data.scrc.uk/api/
  default_input_namespace: soniamitchell
  default_output_namespace: soniamitchell
  write_data_store: /Users/SoniaM/datastore/
  local_repo: /Users/Soniam/Desktop/git/FAIRDataPipeline/FDP_validation/
  latest_commit: 221bfe8b52bbfb3b2dbdc23037b7dd94b49aaa70
  remote_repo: https://github.com/FAIRDataPipeline/FDP_validation
  script: |-
    R -f simple_working_examples/read_array.R /Users/SoniaM/datastore/coderun/20210511-231444/

read:
- data_product: test/array
  use:
    version: 0.1.0
